apiVersion: v1
kind: Service
metadata:
  name: devops-worker-service
  labels:
    app: devops-worker
spec:
  type: NodePort
  selector:
    app: devops-worker
  ports:
    - name: http
      port: 8001
      targetPort: 8001
      nodePort: 30081
      protocol: TCP
